version: 2.1

orbs:
  node: circleci/node@5.2.0

workflows:
  Lint-test-build:
    jobs:
      - node/run:
          name: Lint
          npm-run: lint
      - node/test:
          name: Test
          test-results-for: jest
      - node/run:
          name: Build
          npm-run: build
